/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WS;

/**
 *
 * @author shawn.harden
 */
public class WSForm extends javax.swing.JFrame {

    /**
     * Creates new form DVLForm
     */
    public WSForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jJpesPanel = new javax.swing.JPanel();
        jModeLable = new javax.swing.JLabel();
        jInitialButton = new javax.swing.JRadioButton();
        jMaintenanceButton = new javax.swing.JRadioButton();
        jRefScrollPane = new javax.swing.JScrollPane();
        RefList = new javax.swing.JList<>();
        jReferenceLabel = new javax.swing.JLabel();
        jClearSelectb = new javax.swing.JButton();
        jStartb = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jRxsPanel = new javax.swing.JPanel();
        jGfmdiPanel = new javax.swing.JPanel();
        jDmdcPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DRRS-A Web Services");

        jModeLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jModeLable.setText("Mode:");

        ModeGroup.add(jInitialButton);
        jInitialButton.setText("Intial/Baseline");

        ModeGroup.add(jMaintenanceButton);
        jMaintenanceButton.setText("Maintenance");

        RefList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CargoExtent", "CargoType", "Cin", "Component", "CountryCode", "FmToCinLink", "FmToPinLink", "Geolocation", "Means", "Mod", "ModeSource", "PidComposite", "Pid", "Pin", "SeriesPermission", "Service", "Source", "Split", "StopType", "TuchaCargo3", "TuchaCargo4", "Tucha", "Tudet", "ULNTucha", "UnitLevel", "UnitTypeRecord" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jRefScrollPane.setViewportView(RefList);

        jReferenceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jReferenceLabel.setText("Reference Data:");

        jClearSelectb.setText("Clear Selection");

        jStartb.setText("Start");

        jExitButton.setText("Close");

        javax.swing.GroupLayout jJpesPanelLayout = new javax.swing.GroupLayout(jJpesPanel);
        jJpesPanel.setLayout(jJpesPanelLayout);
        jJpesPanelLayout.setHorizontalGroup(
            jJpesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jJpesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jJpesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jJpesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jInitialButton)
                        .addGap(33, 33, 33)
                        .addComponent(jMaintenanceButton))
                    .addComponent(jModeLable)
                    .addComponent(jReferenceLabel)
                    .addGroup(jJpesPanelLayout.createSequentialGroup()
                        .addComponent(jClearSelectb)
                        .addGap(30, 30, 30)
                        .addComponent(jStartb))
                    .addComponent(jRefScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jJpesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExitButton)
                .addContainerGap())
        );
        jJpesPanelLayout.setVerticalGroup(
            jJpesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jJpesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jModeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jJpesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInitialButton)
                    .addComponent(jMaintenanceButton))
                .addGap(22, 22, 22)
                .addComponent(jReferenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRefScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jJpesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearSelectb)
                    .addComponent(jStartb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jExitButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("JPES", jJpesPanel);

        javax.swing.GroupLayout jRxsPanelLayout = new javax.swing.GroupLayout(jRxsPanel);
        jRxsPanel.setLayout(jRxsPanelLayout);
        jRxsPanelLayout.setHorizontalGroup(
            jRxsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jRxsPanelLayout.setVerticalGroup(
            jRxsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RXS 2.0", jRxsPanel);

        javax.swing.GroupLayout jGfmdiPanelLayout = new javax.swing.GroupLayout(jGfmdiPanel);
        jGfmdiPanel.setLayout(jGfmdiPanelLayout);
        jGfmdiPanelLayout.setHorizontalGroup(
            jGfmdiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jGfmdiPanelLayout.setVerticalGroup(
            jGfmdiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("GFM-DI", jGfmdiPanel);

        javax.swing.GroupLayout jDmdcPanelLayout = new javax.swing.GroupLayout(jDmdcPanel);
        jDmdcPanel.setLayout(jDmdcPanelLayout);
        jDmdcPanelLayout.setHorizontalGroup(
            jDmdcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jDmdcPanelLayout.setVerticalGroup(
            jDmdcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DMDC", jDmdcPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ModeGroup;
    private javax.swing.JList<String> RefList;
    private javax.swing.JButton jClearSelectb;
    private javax.swing.JPanel jDmdcPanel;
    private javax.swing.JButton jExitButton;
    private javax.swing.JPanel jGfmdiPanel;
    private javax.swing.JRadioButton jInitialButton;
    private javax.swing.JPanel jJpesPanel;
    private javax.swing.JRadioButton jMaintenanceButton;
    private javax.swing.JLabel jModeLable;
    private javax.swing.JScrollPane jRefScrollPane;
    private javax.swing.JLabel jReferenceLabel;
    private javax.swing.JPanel jRxsPanel;
    private javax.swing.JButton jStartb;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
